name: NuGet Package Publish - Xreeple.Bukalemun.DependencyInjectionExtensions

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/Xreeple.Bukalemun.DependencyInjectionExtensions.nuspec'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/Xreeple.Bukalemun.DependencyInjectionExtensions.nuspec'
      
jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore src/Xreeple.Bukalemun.DependencyInjectionExtensions/Xreeple.Bukalemun.DependencyInjectionExtensions.csproj

      - name: Publish project
        run: dotnet publish src/Xreeple.Bukalemun.DependencyInjectionExtensions/Xreeple.Bukalemun.DependencyInjectionExtensions.csproj --configuration Release --output publish/Xreeple.Bukalemun.DependencyInjectionExtensions/net9.0 --framework net9.0

      - name: Pack NuGet package
        run: nuget pack src/Xreeple.Bukalemun.DependencyInjectionExtensions/Xreeple.Bukalemun.DependencyInjectionExtensions.nuspec

      - name: Setup NuGet CLI
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Push NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: nuget push *.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}
