name: NuGet Package Publish - Xreeple.Bukalemun.Data

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/Xreeple.Bukalemun.Data.nuspec'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/Xreeple.Bukalemun.Data.nuspec'
      
jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore src/Xreeple.Bukalemun.Data/Xreeple.Bukalemun.Data.csproj

      - name: Pack NuGet package
        run: dotnet pack src/Xreeple.Bukalemun.Data/Xreeple.Bukalemun.Data.csproj -c Release -p:NuspecFile=Xreeple.Bukalemun.Data.nuspec
        
      - name: Push NuGet package
        shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push src/Xreeple.Bukalemun.Data/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
