<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net7.0;net9.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="C:\Users\mehmet.eker\.nuget\packages\cryptonet\2.4.0\contentFiles\any\netstandard2.0\CryptoNetLogo-icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="CryptoNet" Version="2.4.0" />
  </ItemGroup>
</Project>
